version: '3'
services:
  discovery-server:
    build: ./discovery-server
    ports:
      - "8761:8761"
    container_name: discovery-service

  product-service:
    build: ./product-service
    ports:
      - "6000:6000"
    depends_on:
      - discovery-server
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://discovery-service:8761/eureka/
    container_name: product-service

  payment_service:
    build: ./payment_service
    ports:
      - "6002:6002"
    depends_on:
      - discovery-server
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://discovery-service:8761/eureka/
    container_name: payment-service

  order_service:
    build: ./order_service
    ports:
      - "6001:6001"
    depends_on:
      - discovery-server
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://discovery-service:8761/eureka/
    container_name: order_service

  apigateway:
    build: ./apigateway
    ports:
      - "5000:5000"
    depends_on:
      - discovery-server
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://discovery-service:8761/eureka/
    container_name: apigateway