spring:
  cloud:
    gateway:
      server:
        webflux:
          discovery:
            locator:
              lower-case-service-id: true
              enabled: true
      routes:
        - id: product-service-route
          uri: lb://product-service
          predicates:
            - Path=/products/**, /categories/**
          filters:
            - name: RequestRateLimiter
              args:
                key-resolver: "#{@ipKeyResolver}"
                redis-rate-limiter.replenishRate: 2
                redis-rate-limiter.burstCapacity: 2
            - name: CircuitBreaker
              args:
                name: productServiceCircuitBreaker
                fallbackUri: forward:/fallback/product


        - id: order-service-route
          uri: http://localhost:6001
          predicates:
            - Path=/orders/**

        - id: payment-service-route
          uri: http://localhost:6002
          predicates:
            - Path=/payments/**

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/